### ISSUE TITLE
执行npm run 命令失败

### ISSUE THREAD

**Issue by JasonCSharpCoder** [liujians/vue-adminLte-vue-router#4]
作者你好，按照你提供的安装和启动方式，安装没有问题，但是在执行npm run dev
'caniuse-db/features-json/transforms2d.json 请问这个，需要安装什么？

**Comment by liujians** [comment]
@JasonCSharpCoder 您好，是否可以贴出更详细的错误信息或者截图呢？

**Comment by qianthinkover** [comment]
[
![m3g9bem h_chg4 hv4kriu](https://cloud.githubusercontent.com/assets/3151832/20082157/12c90bc4-a58f-11e6-95ea-f8459726a539.png)
](url)

您好！错误如图，我重新配置了一次，还是不行，

**Comment by liujians** [comment]
@qianthinkover 您好，我这里重新尝试了一下没有遇到这个问题、您所缺少的文件我这里重新安装也依然下载到了、请尝试升级node到更新的版本、或者尝试下重新安装依赖
![image](https://cloud.githubusercontent.com/assets/22309837/20084508/b9325980-a59d-11e6-9939-e91a5c227fbf.png)
![image](https://cloud.githubusercontent.com/assets/22309837/20084520/d6a414e0-a59d-11e6-9065-40dbf9c3fd37.png)

**Comment by zion223** [comment]
应该是他们直接下载了，应该用git命令才可以

**Comment by niniun1024** [comment]
你好，npm run dev报下面的错，node版本换到4.4..4还是报错
--------------------------------
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'D:\\Program Files (x86)\\Nodist\\bin\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'dev' ]
2 info using npm@3.9.5
3 info using node@v5.3.0
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle hms@1.0.0~predev: hms@1.0.0
6 silly lifecycle hms@1.0.0~predev: no script for predev, continuing
7 info lifecycle hms@1.0.0~dev: hms@1.0.0
8 verbose lifecycle hms@1.0.0~dev: unsafe-perm in lifecycle true
9 verbose lifecycle hms@1.0.0~dev: PATH: D:\Program Files (x86)\Nodist\bin\node_modules\npm\bin\node-gyp-bin;F:\vue\project\vue-adminLte\node_modules\.bin;C:\Program Files\nodejs;D:\Program Files\ImageMagick-6.9.2-Q16;d:\program files\graphicsmagick-1.3.21-q16;C:\ProgramData\Oracle\Java\javapath;C:\Perl64\site\bin;C:\Perl64\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;D:\soft\TortoiseSVN\bin;C:\Program Files (x86)\Windows Kits\8.0\Windows Performance Toolkit\;D:\Program Files\Java\jdk1.8.0_45bin;D:\Program Files (x86)\apache-ant-1.9.4bin;%ANDROID_HOME%platform-tools;%ANDROID_HOME%tools;D:\Program Files\apache-ant-1.9.4\bin;D:\Program Files\Java\jdk1.8.0_45\bin;D:\Program Files\adt-bundle-windows-x86_64-20131030\sdk\platform-tools;D:\Program Files\adt-bundle-windows-x86_64-20131030\sdk\tools;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files (x86)\Intel\OpenCL SDK\3.0\bin\x86;C:\Program Files (x86)\Intel\OpenCL SDK\3.0\bin\x64;C:\Program Files\Lenovo\Fingerprint Manager Pro\;E:\soft\xampp\php;D:\Program Files\GraphicsMagick-1.3.21-Q16;D:\Program Files\ImageMagick-6.9.2-Q16;D:\Program Files\nvmw;D:\Program Files\nvm;D:\nvm;C:\Program Files\nodejs;D:\Program Files (x86)\Nodist\bin;D:\Program Files\python;C:\Program Files (x86)\Git\bin;C:\Ruby200-x64\bin;C:\RailsInstaller\Git\cmd;C:\RailsInstaller\Ruby1.9.3\bin;D:\Program Files\Java\jdk1.8.0_45\jre;D:\java\programfile\maven\bin;E:\soft\xampp\php\;C:\Users\Xiao106347\.nvmw;C:\Users\Xiao106347\AppData\Roaming\npm;D:\Program Files (x86)\UltraEdit\;C:\Users\Xiao106347\AppData\Local\atom\bin
10 verbose lifecycle hms@1.0.0~dev: CWD: F:\vue\project\vue-adminLte
11 silly lifecycle hms@1.0.0~dev: Args: [ '/d /s /c', 'node build/dev-server.js' ]
12 silly lifecycle hms@1.0.0~dev: Returned: code: 1  signal: null
13 info lifecycle hms@1.0.0~dev: Failed to exec dev script
14 verbose stack Error: hms@1.0.0 dev: `node build/dev-server.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (D:\Program Files (x86)\Nodist\bin\node_modules\npm\lib\utils\lifecycle.js:245:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (D:\Program Files (x86)\Nodist\bin\node_modules\npm\lib\utils\spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:818:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid hms@1.0.0
16 verbose cwd F:\vue\project\vue-adminLte
17 error Windows_NT 6.2.9200
18 error argv "C:\\Program Files\\nodejs\\node.exe" "D:\\Program Files (x86)\\Nodist\\bin\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
19 error node v5.3.0
20 error npm  v3.9.5
21 error code ELIFECYCLE
22 error hms@1.0.0 dev: `node build/dev-server.js`
22 error Exit status 1
23 error Failed at the hms@1.0.0 dev script 'node build/dev-server.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the hms package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node build/dev-server.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs hms
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls hms
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by JasonCSharpCoder** [comment]
我把node 卸载安装6.0稳定版后重启机器 就可以了

At 2016-11-22 11:54:43, "jyy12" notifications@github.com wrote:

你好，npm run dev报下面的错，node版本换到4.4..4还是报错

0 info it worked if it ends with ok
1 verbose cli [ 'C:\Program Files\nodejs\node.exe',
1 verbose cli 'D:\Program Files (x86)\Nodist\bin\node_modules\npm\bin\npm-cli.js',
1 verbose cli 'run',
1 verbose cli 'dev' ]
2 info using npm@3.9.5
3 info using node@v5.3.0
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle hms@1.0.0predev: hms@1.0.0
6 silly lifecycle hms@1.0.0predev: no script for predev, continuing
7 info lifecycle hms@1.0.0dev: hms@1.0.0
8 verbose lifecycle hms@1.0.0dev: unsafe-perm in lifecycle true
9 verbose lifecycle hms@1.0.0dev: PATH: D:\Program Files (x86)\Nodist\bin\node_modules\npm\bin\node-gyp-bin;F:\vue\project\vue-adminLte\node_modules.bin;C:\Program Files\nodejs;D:\Program Files\ImageMagick-6.9.2-Q16;d:\program files\graphicsmagick-1.3.21-q16;C:\ProgramData\Oracle\Java\javapath;C:\Perl64\site\bin;C:\Perl64\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;D:\soft\TortoiseSVN\bin;C:\Program Files (x86)\Windows Kits\8.0\Windows Performance Toolkit;D:\Program Files\Java\jdk1.8.0_45bin;D:\Program Files (x86)\apache-ant-1.9.4bin;%ANDROID_HOME%platform-tools;%ANDROID_HOME%tools;D:\Program Files\apache-ant-1.9.4\bin;D:\Program Files\Java\jdk1.8.0_45\bin;D:\Program Files\adt-bundle-windows-x86_64-20131030\sdk\platform-tools;D:\Program Files\adt-bundle-windows-x86_64-20131030\sdk\tools;C:\Program Files\Intel\WiFi\bin;C:\Program Files\Common Files\Intel\WirelessCommon;C:\Program Files (x86)\Intel\OpenCL SDK\3.0\bin\x86;C:\Program Files (x86)\Intel\OpenCL SDK\3.0\bin\x64;C:\Program Files\Lenovo\Fingerprint Manager Pro;E:\soft\xampp\php;D:\Program Files\GraphicsMagick-1.3.21-Q16;D:\Program Files\ImageMagick-6.9.2-Q16;D:\Program Files\nvmw;D:\Program Files\nvm;D:\nvm;C:\Program Files\nodejs;D:\Program Files (x86)\Nodist\bin;D:\Program Files\python;C:\Program Files (x86)\Git\bin;C:\Ruby200-x64\bin;C:\RailsInstaller\Git\cmd;C:\RailsInstaller\Ruby1.9.3\bin;D:\Program Files\Java\jdk1.8.0_45\jre;D:\java\programfile\maven\bin;E:\soft\xampp\php;C:\Users\Xiao106347.nvmw;C:\Users\Xiao106347\AppData\Roaming\npm;D:\Program Files (x86)\UltraEdit;C:\Users\Xiao106347\AppData\Local\atom\bin
10 verbose lifecycle hms@1.0.0dev: CWD: F:\vue\project\vue-adminLte
11 silly lifecycle hms@1.0.0dev: Args: [ '/d /s /c', 'node build/dev-server.js' ]
12 silly lifecycle hms@1.0.0dev: Returned: code: 1 signal: null
13 info lifecycle hms@1.0.0~dev: Failed to exec dev script
14 verbose stack Error: hms@1.0.0 dev: node build/dev-server.js
14 verbose stack Exit status 1
14 verbose stack at EventEmitter. (D:\Program Files (x86)\Nodist\bin\node_modules\npm\lib\utils\lifecycle.js:245:16)
14 verbose stack at emitTwo (events.js:87:13)
14 verbose stack at EventEmitter.emit (events.js:172:7)
14 verbose stack at ChildProcess. (D:\Program Files (x86)\Nodist\bin\node_modules\npm\lib\utils\spawn.js:24:14)
14 verbose stack at emitTwo (events.js:87:13)
14 verbose stack at ChildProcess.emit (events.js:172:7)
14 verbose stack at maybeClose (internal/child_process.js:818:16)
14 verbose stack at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid hms@1.0.0
16 verbose cwd F:\vue\project\vue-adminLte
17 error Windows_NT 6.2.9200
18 error argv "C:\Program Files\nodejs\node.exe" "D:\Program Files (x86)\Nodist\bin\node_modules\npm\bin\npm-cli.js" "run" "dev"
19 error node v5.3.0
20 error npm v3.9.5
21 error code ELIFECYCLE
22 error hms@1.0.0 dev: node build/dev-server.js
22 error Exit status 1
23 error Failed at the hms@1.0.0 dev script 'node build/dev-server.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the hms package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error node build/dev-server.js
23 error You can get information on how to open an issue for this project with:
23 error npm bugs hms
23 error Or if that isn't available, you can get their info via:
23 error npm owner ls hms
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by williamjie** [comment]
之前遇到过这种问题，重新下载代码（重新执行npm install  老版本下载的是老的各种兼容包）

**Comment by yutao23** [comment]
改了项目名之后就打不开了
